#
# The resulting image of this Dockerfile would have oracle linux and oracle weblogic 1221  and osb1221 installed and scripts to create domain
#
# ----------------------------------
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) container-scripts
#
#
# ---------------
# Pull base image
# ---------------
FROM soa:scripts-loaded

# ----------
# Maintainer
# ----------
MAINTAINER Zheng Liang <zheng.liang@precise-soft.com>

CMD ["/u01/oracle/container-scripts/createAndStartManagedServer.sh"]
